[package]
name = "dogfood"
version = "0.1.0"
authors = ["Richard Dallaway <richard@dallaway.com>"]
edition = "2018"

[dependencies]
num-rational = "0.3"
take-until = "0.1.0"
itertools = "0.9.0"
lazy_static = "1.4"