[package]
name = "dogfood"
version = "0.1.0"
authors = ["Richard Dallaway <richard@dallaway.com>"]
edition = "2018"

[dependencies]
num-traits = "0.2"
num-rational = "0.3"
take-until = "0.1"
itertools = "0.9"
lazy_static = "1.4"
svg = "0.8"
structopt = "0.3"